version: 2
jobs:
  # Define in CircleCi Project Variables: $DOCKERHUB_REPO, $DOCKERHUB_USER, $DOCKERHUB_PASS
  # Publish jobs require those variables
  amd64:
    machine:
      docker_layer_caching: false
    steps:
      - checkout
      - run:
          command: |
            sudo docker login --username=$DOCKERHUB_USER --password=$DOCKERHUB_PASS
            sudo docker build --pull -t $DOCKERHUB_REPO:test-amd64 -f Dockerfile .
            sudo docker push $DOCKERHUB_REPO:test-amd64
  arm32v7:
    machine:
      docker_layer_caching: false
    steps:
      - checkout
      - run:
          command: |
            sudo docker run --rm --privileged multiarch/qemu-user-static:register --reset
            #
            sudo docker login --username=$DOCKERHUB_USER --password=$DOCKERHUB_PASS
            sudo docker build --pull -t $DOCKERHUB_REPO:test-arm32v7 -f testarm32v7.Dockerfile .
            sudo docker push $DOCKERHUB_REPO:test-arm32v7
  arm64v8:
    machine:
      docker_layer_caching: false
    steps:
      - checkout
      - run:
          command: |
            sudo docker run --rm --privileged multiarch/qemu-user-static:register --reset
            #
            sudo docker login --username=$DOCKERHUB_USER --password=$DOCKERHUB_PASS
            sudo docker build --pull -t $DOCKERHUB_REPO:test-arm64v8 -f arm64v8.Dockerfile .
            sudo docker push $DOCKERHUB_REPO:test-arm64v8
  multiarch:
    machine:
      enabled: true
      image: circleci/classic:201808-01
    steps:
      - run:
          command: |
            # Turn on Experimental features
            sudo mkdir $HOME/.docker
            sudo sh -c 'echo "{ \"experimental\": \"enabled\" }" >> $HOME/.docker/config.json'
            #
            sudo docker login --username=$DOCKERHUB_USER --password=$DOCKERHUB_PASS
            #
            sudo docker manifest create --amend $DOCKERHUB_REPO:test $DOCKERHUB_REPO:test-amd64 $DOCKERHUB_REPO:test-arm32v7 $DOCKERHUB_REPO:test-arm64v8
            sudo docker manifest annotate $DOCKERHUB_REPO:test $DOCKERHUB_REPO:test-amd64 --os linux --arch amd64
            sudo docker manifest annotate $DOCKERHUB_REPO:test $DOCKERHUB_REPO:test-arm32v7 --os linux --arch arm --variant v7
            sudo docker manifest annotate $DOCKERHUB_REPO:test $DOCKERHUB_REPO:test-arm64v8 --os linux --arch arm64 --variant v8
            sudo docker manifest push $DOCKERHUB_REPO:test -p

workflows:
  version: 2
  publish:
    jobs:
      - amd64:
          filters:
            branches:
              only:
                - ci/circleci-testing
      - arm32v7:
          filters:
            branches:
              only:
                - ci/circleci-testing
      - arm64v8:
          filters:
            branches:
              only:
                - ci/circleci-testing
      - multiarch:
          requires:
            - arm32v7
            - arm64v8
          filters:
            branches:
              only:
                - ci/circleci-testing
